### ISSUE TITLE
Follow https://www.w3.org/TR/2018/REC-WCAG21-20180605/#meaningful-sequence

### ISSUE THREAD

**Issue by polarbirke** [webfactory/disclosure#1]
See https://github.com/webfactory/gemeinsamer-bundesausschuss/commit/e5979073ff85715f77bce7773fba74a6d577ec5b for reference.

**Comment by mpdude** [comment]
Fixed via 4e5b30b1e2b89fad86338139605b25b585b14d61. Use the new `buttonPositionBelow` option (`true`/`false`).

Default is (for the time being) `true` to maintain BC.
